### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by albert-olive** [jxnblk/reflexbox#61]
Hi,

When upgrading to 3.0.0-0 I'm having this error:

```javascript
node_modules/reflexbox/dist/sheet.js:7
var style = document.createElement('style');
                     ^

ReferenceError: document is not defined
    at Object.<anonymous> (/Users/Repos/web/node_modules/reflexbox/dist/sheet.js:7:22)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Repos/web/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.cls_wrapMethod [as _load] (/Users/Repos/web/node_modules/newrelic/lib/shimmer.js:256:38)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

Anybody have this too?

[EDIT] - v2.2.2 works fine.

Thanks

**Comment by jxnblk** [comment]
v3 is a rewrite and doesn't currently work in SSR, see https://github.com/jxnblk/reflexbox#caveats

v2 will continue to work, but if you want something that uses css-in-js, maybe consider https://github.com/jxnblk/grid-styled

**Comment by albert-olive** [comment]
Ok, thank you for your response. We use SSR and that's why. We'll look something else.

**Comment by jcollum** [comment]
Could you clarify that caveat? I'm unclear what you mean by server-side applications since this is a React library.
